[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
favorites = "9qQHP1ngQnJfY4FTyguiPv3cWDKDcpfkZJZd7NRHPaGQ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
